# Generated by Django 4.1.7 on 2023-03-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0005_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
