# Generated by Django 4.1.7 on 2023-03-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(null=True, to='scmapp.tag'),
        ),
    ]
