# Generated by Django 4.1.7 on 2023-04-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0009_customer_user_alter_customer_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
