# Generated by Django 4.1.7 on 2023-04-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0011_alter_customer_profile_pic_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
